version: '3.5'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
    go:
      build: ./app
      volumes:
        - ./app:/go/src/app
      working_dir: /go/src/app
      environment:
        TZ: Asia/Tokyo
      ports:
#        - "8080:8080"
        - "2345:2345"
      tty: true
      security_opt:
        - apparmor:unconfined
      cap_add:
        - SYS_PTRACE
      networks:
        - frontend
        - backend

    mysql:
      build: ./mysql
      platform: linux/amd64 # for M1 tip
      environment:
        - TZ=Asia/Tokyo
        - MYSQL_DATABASE=flowers
        - MYSQL_USER=flowers
        - MYSQL_PASSWORD=flowers
        - MYSQL_ROOT_PASSWORD=root
#      restart: always
      ports:
        - "3306:3306"
      volumes:
        - ~/.godock/mysql/data:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      networks:
        - backend

    nginx:
        container_name: "nginx"
        build: ./nginx
        ports:
          - "8000:80"
        depends_on:
          - "go"
        networks:
          - frontend
          - backend
